### ISSUE TITLE
Incompatible ClearMap 1 .npy output files 

### ISSUE THREAD

**Issue by sgoldenlab** [ClearAnatomics/ClearMap#1]
**Goal:** To annotate and segment ClearMap1-generated .npy files in ClearMap2, due to a ClearMap1 bug that alters the output of full regional hierarchy in the annotated cell count .csv output file. 

**Problem:** Attempts to load and define ClearMap1 .npy files "cells.npy" and "cells_transformed_to_atlas.npy" as the ClearMap2 variables "cells_filtered" and "coordinates_transformed" respectively, results in the following error:

IndexError: tuple index out of range

Therefore, existing ClearMap2 code does not provide compatibility with ClearMap1-generated .npy files due to differences in file structure.

**Recommended solution:** Provide code in ClearMap2 that will reformat ClearMap1 .npy files into a structure that is compatible with with the Data Generation and CSV Export sections of code within the CellMap.py script.

**Comment by sgoldenlab** [comment]
Is there anything simple we can try to make the files compatible with CM2?

**Comment by ChristophKirst** [comment]
The output is also a numpy array as in ClearMap 1 but with additional column names that indicate the various measured quantities . So reading the data should be straight forward using classical numpy readers, and then exporting the correct columns into the desired output format.

For large number of cells I don't recommend CSV files.

Hope that helps.

**Comment by ChristophKirst** [comment]
ps: check out the CellMap.py script to see how to add column names etc.

**Comment by sgoldenlab** [comment]
Thanks, will try. Can you provide a sample output from CM2 so we know what the headers should be?

**Comment by sgoldenlab** [comment]
@ChristophKirst

**Comment by ChristophKirst** [comment]
There is a cell in the CellMap tutorial that shows this.
