### ISSUE TITLE
Default parameters for artery binarization in Tubemap.py

### ISSUE THREAD

**Issue by PTRRupprecht** [ClearAnatomics/ClearMap#11]
First of all, great package! I tried to run the Tubemap.py script on your test brain samples and encountered a small error in line 272 ("processing_parameter = vasc.default_processing_parameter.copy()").
"default_processing_parameter" cannot be found and throws an error.

I replaced the line with "processing_parameter = vasc.default_binarization_processing_parameter.copy()". Is this still correct, or am I missing something?

**Comment by ChristophKirst** [comment]
Thats correct, thank you for spotting it ! 
It is now corrected in the new version.
