### ISSUE TITLE
Smoothing.npy

### ISSUE THREAD

**Issue by PTRRupprecht** [ClearAnatomics/ClearMap#12]
Another small issue: During the smoothing operation, a pre-calculated look-up-table is used, which is saved in ClearMap2/ClearMap/ImageProcessing/Binary/Smoothing.npy, or in the zip-file. I'm not sure whether the file in the zip-file is intact, because it did not work in my case. I therefore recomputed the LUT from scratch, but this takes quite long. Maybe you can check whether the zip file contains an intact npy file?

**Comment by ChristophKirst** [comment]
Hi,
i am not sure why this is.
If you move the `Smoothing.npy` file to a different folder (for backup) but keep the `zip` file
and then try:

    import os
    import ClearMap.ImageProcessing.Smoothing as sm
    filename = os.path.join(os.path.dirname(os.path.abspath(sm.__file__)), sm.smooth_by_configuration_filename);
    sm.fu.uncompress(filename, verbose=True)

and see what the output is ?
If there are errors does 

    import zipfile 

give you any errors ?

**Comment by PTRRupprecht** [comment]
Thanks for the replies!

If I execute your code, the npy-file is properly generated and has the same file size as it should have. Maybe there is no problem after all? I'm wondering why it did not work when I ran the smoothing code in the beginning. But maybe it's okay to close the issue -- right now, I'm anyway using the previously generated npy-file, so I don't have any real issues.

**Comment by ChristophKirst** [comment]
I tested with a new install, and i did not get the error / the zip file uncompressed without problem.
Closing this for now.
