### ISSUE TITLE
Clarification on CPU vs GPU performance for CellMap

### ISSUE THREAD

**Issue by pderdeyn** [ClearAnatomics/ClearMap#13]
Hi Christoph,
This is more of a feature/documentation request than an issue. My apologies if I have missed it somewhere

My team would like to know if this can run CPU-only. We have noticed some functions have CPU-only options, but it is not clear how much of the pipeline we can access this way. We are specifically interested in CellMap for now

Likewise (and this is a separate but related request), do you have any performance metrics on CellMap in ClearMap2 (with GPU; CPU-only would also be interesting tho) vs ClearMap1? My team is excited about the opportunity to accelerate our pipeline, but to justify the cost of a GPU we would like some more information. In the absence of metrics, just a gut feel about the acceleration would also be helpful

Let me know if you would like more information or clarification.

-Pieter

**Comment by ChristophKirst** [comment]
Hi Pieter,

Currently CellMap is cpu only, no need for a GPU. A gpu can speed up the neural network computation in tubemap but is not necessary. We will clarify this in the hardware requirements. Hope that helps?

**Comment by pderdeyn** [comment]
Thanks! This is satisfactory for me. I'm looking forward to trying out CellMap soon.

If you wish to close the issue that's fine with me. I would suggest clarification in the documentation about this hardware requirement

**Comment by ChristophKirst** [comment]
Thanks for the ocmments. 

We now list the hardware we use for our data in the documentation:

https://christophkirst.github.io/ClearMap2Documentation/html/installation.html#computing-resources
