### ISSUE TITLE
On import ClearMap.Environment getting 'command 'gcc' failed with exit status 1', macOS

### ISSUE THREAD

**Issue by cudmore** [ClearAnatomics/ClearMap#15]
Hi there,

I am trying to get started running your example TubeMap scripts and am running into errors using `gcc`. I am on `macOS 10.12.6` using `conda 4.7.12`. Does ClearMap run on macOS? Any pointers in how to troubleshoot would be appreciated.

First, install

```
git clone https://github.com/ChristophKirst/ClearMap2.git
cd ClearMap2
conda env create -f ClearMap.yml
conda activate ClearMap
```

Then in an ipython prompt:

```
from ClearMap.Environment import *
```

Results in gcc errors

```
clang: error: unsupported option '-fopenmp'
...
DistutilsExecError: command 'gcc' failed with exit status 1
...
~/anaconda3/envs/ClearMap/lib/python3.7/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    119         except DistutilsExecError as msg:
--> 120             raise CompileError(msg)
    121 

CompileError: command 'gcc' failed with exit status 1
```

When I am in the conda ClearMap environment, gcc is still in `/usr/bin/gcc`.

```
which gcc
```

Gives

```
/usr/bin/gcc
```

I tried installing gcc inside conda with `conda install gcc` but get `PackageNotFound`. I am using `conda 4.7.12` and as far as I understand, conda before version 5 were using system level gcc. After version 5 they use their own gcc installers. This would explain why 'conda install gcc' is failing?

Finally, `/usr/bin/gcc -v` gives me:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Do you know of any env paths I can set so your clearmap compile steps can find gcc?

**Comment by ChristophKirst** [comment]
The erorr shows:
unsupported option -fopenmp

which points to a missing multiprocessing library OpenMP / MPI 

Installing that library might fix the problem ? I fit is installed making its path available could help too.

We don't run ClearMap under Mac at this point, so I cannot be of much more help how to do that (possibly homebrew 
or similar tools?) A software company is working on making the software available on Mac and Windows 
 (though this might take several months).

Hope that helps ?

**Comment by cudmore** [comment]
Thanks for the info and solid lead about `OpenMP`. Looks like the stock `clang` on macOS (Sierra) does not support the multiprocessing library (OpenMP) out of the box. See [Enable OpenMP support in clang in Mac OS X...](https://stackoverflow.com/questions/43555410/enable-openmp-support-in-clang-in-mac-os-x-sierra-mojave) for some tips.

**Caveat**: If your on macOS, no guarantee this will work. This was done on an older version (Sierra) and might not work on other versions. Also, I got ClearMap to compile but now can't really test if this compilation actually works as the pipeline for the full brain example data on [osf.io/q6atb](https://osf.io/q6atb/) is way too big for my machine, [see my post here](https://github.com/ChristophKirst/ClearMap2/issues/2). Would be great if we had a toy example with maybe 4 stacks rather than 100's? Goal would be for non-super-humans/computer to run the code :)

I got ClearMap to compile in two main steps:

### 1. Install llvm and libomp

```
brew update # took >1 hour
brew install llvm libomp 
```
The important llvm file is now in `/usr/local/opt/llvm/include`

### 2. Modify Python source code in conda environment

Need to modify the file `envs/ClearMap/lib/python3.7/distutils/unixccompiler.py` as follows ...

Basically, each time `-fopenmp` is passed to both compile and link steps, it needs to be preceded with the path to llvm, `/usr/local/opt/llvm/include`. Like this `-I/usr/local/opt/llvm/include -fopenmp`.

In `def _compile()`

```
       # start added by bob
       if extra_postargs:
        	if extra_postargs[-1] == '-fopenmp':
        		extra_postargs[-1] = '-I/usr/local/opt/llvm/include -fopenmp'        
       # end added by bob
       try:
            self.spawn(compiler_so + cc_args + [src, '-o', obj] +
                       extra_postargs)
        except DistutilsExecError as msg:
            raise CompileError(msg)
```
In `def link()`

```
                # start added by bob
                if ld_args:
        	        if ld_args[-1] == '-fopenmp':
        	        	ld_args[-1] = '-I/usr/local/opt/llvm/include -fopenmp'
                # end added by bob
                self.spawn(linker + ld_args) # original code
```

Then at an ipython prompt, the following works

```
import ClearMap.Compile 
```

Hope this helps some people on macOS?

**Comment by ywang219** [comment]
Thanks for the detailed solutions. I am also running it on macOS (catalina) having the same issue. Want to clarify with your step2 modifying python code: did you mean to replace the entire def_compile() and def link() with yours or add on to the original code, if so, where exactly? Thanks!

**Comment by ywang219** [comment]
> Thanks for the info and solid lead about `OpenMP`. Looks like the stock `clang` on macOS (Sierra) does not support the multiprocessing library (OpenMP) out of the box. See [Enable OpenMP support in clang in Mac OS X...](https://stackoverflow.com/questions/43555410/enable-openmp-support-in-clang-in-mac-os-x-sierra-mojave) for some tips.
> 
> **Caveat**: If your on macOS, no guarantee this will work. This was done on an older version (Sierra) and might not work on other versions. Also, I got ClearMap to compile but now can't really test if this compilation actually works as the pipeline for the full brain example data on [osf.io/q6atb](https://osf.io/q6atb/) is way too big for my machine, [see my post here](https://github.com/ChristophKirst/ClearMap2/issues/2). Would be great if we had a toy example with maybe 4 stacks rather than 100's? Goal would be for non-super-humans/computer to run the code :)
> 
> I got ClearMap to compile in two main steps:
> 
> ### 1. Install llvm and libomp
> ```
> brew update # took >1 hour
> brew install llvm libomp 
> ```
> 
> The important llvm file is now in `/usr/local/opt/llvm/include`
> 
> ### 2. Modify Python source code in conda environment
> Need to modify the file `envs/ClearMap/lib/python3.7/distutils/unixccompiler.py` as follows ...
> 
> Basically, each time `-fopenmp` is passed to both compile and link steps, it needs to be preceded with the path to llvm, `/usr/local/opt/llvm/include`. Like this `-I/usr/local/opt/llvm/include -fopenmp`.
> 
> In `def _compile()`
> 
> ```
>        # start added by bob
>        if extra_postargs:
>         	if extra_postargs[-1] == '-fopenmp':
>         		extra_postargs[-1] = '-I/usr/local/opt/llvm/include -fopenmp'        
>        # end added by bob
>        try:
>             self.spawn(compiler_so + cc_args + [src, '-o', obj] +
>                        extra_postargs)
>         except DistutilsExecError as msg:
>             raise CompileError(msg)
> ```
> 
> In `def link()`
> 
> ```
>                 # start added by bob
>                 if ld_args:
>         	        if ld_args[-1] == '-fopenmp':
>         	        	ld_args[-1] = '-I/usr/local/opt/llvm/include -fopenmp'
>                 # end added by bob
>                 self.spawn(linker + ld_args) # original code
> ```
> 
> Then at an ipython prompt, the following works
> 
> ```
> import ClearMap.Compile 
> ```
> 
> Hope this helps some people on macOS?

Thanks for the detailed solutions. I am also running it on macOS (catalina) having the same issue. Want to clarify with your step2 modifying python code: did you mean to replace the entire def_compile() and def link() with yours or add on to the original code, if so, where exactly? Thanks!

**Comment by ChristophKirst** [comment]
Thanks for figuring this out !
We will include this in our updates!

**Comment by ChristophKirst** [comment]
This seems fixed, I am closing this issue. Feel free to reopen.

**Comment by Yannan-Chen** [comment]
Faced same problem but on Ubuntu 20.04.3. Solved by running:

sudo apt-get install g++
