### ISSUE TITLE
CellMap Dataset

### ISSUE THREAD

**Issue by SaibotMagd** [ClearAnatomics/ClearMap#16]
Hi,

I can't find the Dataset you use for the CellMap Tutorial. Is this provided?

**Comment by saskra** [comment]
https://osf.io/sa3x8/files/?view_only=4427a838cbd0468c9fbad9cab465d866

**Comment by SaibotMagd** [comment]
Thank you

**Comment by SaibotMagd** [comment]
I think the Tutorial files for Cellmap are here: [https://osf.io/rp2ev/](url) [about 100gb]
and the files for the Tubemap Tutorial here: [https://osf.io/sa3x8/](url) [about 3TB]

**Comment by SaibotMagd** [comment]
Mr. Renier uploaded a new Dataset to test the CellMap Pipeline because of the weak quality and the old slice picture method in the 2016 Dataset.
The new Dataset can be found here: https://osf.io/cztq2/ (it's in tiles now so you have to stitch the tiles)
