### ISSUE TITLE
MHD Creater Function is changing the dimension order

### ISSUE THREAD

**Issue by SaibotMagd** [ClearAnatomics/ClearMap#20]
Question = Solution here (I should try out the pull request function).

The function:
`io.mhd.write_header_from_source(ws.filename('stitched'))`

Creates a MHD file with parameter `DimSize = 1892 2671 1802`out of a stitched-npy with shape = (1802, 2671, 1892) so the imageJ view is broken.
I changed the order in the DimSize parameter by hand and it works out just fine.

**Comment by ChristophKirst** [comment]
I fixed this in the new commit, however its important to note:

If your numpy array is in Fortran order, this should work fine now.

If it is in C order, it will also work keeping the array content, however the axes in the array will be transposed when viewed in imagej.
