### ISSUE TITLE
ERROR: problem defining fixed image dimension + align: failed executing: ' + cmd

### ISSUE THREAD

**Issue by ywang219** [ClearAnatomics/ClearMap#24]
Hello,
I am at this step:
----------------------------------------------------
# align the two channels
align_channels_parameter = {
    #moving and reference images
    "moving_image" : ws.filename('resampled', postfix='autofluorescence'),
    "fixed_image"  : ws.filename('resampled'),

    #elastix parameter files for alignment
    "affine_parameter_file"  : align_channels_affine_file,
    "bspline_parameter_file" : None,

    #directory of the alig'/home/nicolas.renier/Documents/ClearMap_Ressources/Par0000affine.txt',nment result
    "result_directory" :  ws.filename('elastix_resampled_to_auto')
    };

elx.align(**align_channels_parameter);

-----------------------------------------
However, I ran in to issue: 

Running elastix with parameter file 0: "/home/yidan/ClearMap2/ClearMap/Resources/Alignment/align_affine.txt".

Current time: Fri Jul 24 13:03:12 2020.
Reading the elastix parameters from file ...

ERROR: problem defining fixed image dimension.
  The parameter file says:     3
  The fixed image header says: 2
  Note that from elastix 4.6 the parameter file definition "FixedImageDimension" is not needed anymore.
  Please remove this entry from your parameter file.
Errors occurred!

Thank you for your time!

**Comment by SaibotMagd** [comment]
Did you stitch the Data before you run the alignment? Use:

```
s = ws.source('raw') 
print(s)
print(s.shape)

```

**Comment by ywang219** [comment]
> s = ws.source('raw') 
> print(s)
> print(s.shape)

Hi, thank you for the response. It doesn't seem to resolve the issue...


the same error came up:

~/ClearMap2/ClearMap/Alignment/Elastix.py in align(fixed_image, moving_image, affine_parameter_file, bspline_parameter_file, result_directory, processes)
    550 
    551   if res != 0:
--> 552     raise RuntimeError('align: failed executing: ' + cmd);
    553 
    554   return result_directory

RuntimeError: align: failed executing: /home/yidan/ClearMap2/ClearMap/External/elastix/build/bin/elastix -threads 1 -m /home/yidan/test/brain7test/resampled_autofluorescence.tif -f /home/yidan/test/brain7test/resampled.tif -p /home/yidan/ClearMap2/ClearMap/Resources/Alignment/align_affine.txt -out /home/yidan/test/brain7test/elastix_resampled_to_auto

**Comment by SaibotMagd** [comment]
But this is another problem. Now it seems like he can't find the files. Did you check if every file is in the right folder? 
Also try to change the parameter to:

`"result_directory" :  ws.filename('resampled_to_auto')" `

aka delete the "elastix_". I think the last update solved this problem.

**Comment by ywang219** [comment]
> But this is another problem. Now it seems like he can't find the files. Did you check if every file is in the right folder?
> Also try to change the parameter to:
> 
> `"result_directory" : ws.filename('resampled_to_auto')" `
> 
> aka delete the "elastix_". I think the last update solved this problem.

Thank you for your help! oops my bad. Yes there are 2 problems at once. And I did delete the "elastix_", the same 2 problems still occur. 

I checked that files are in the right folder. 



--------------------------------------------



Running elastix with parameter file 0: "/home/yidan/ClearMap2/ClearMap/Resources/Alignment/align_affine.txt".

Current time: Tue Jul 28 10:39:03 2020.
Reading the elastix parameters from file ...

ERROR: problem defining fixed image dimension.
  The parameter file says:     3
  The fixed image header says: 2
  Note that from elastix 4.6 the parameter file definition "FixedImageDimension" is not needed anymore.
  Please remove this entry from your parameter file.
Errors occurred!
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-be114c2c0f74> in <module>
     13     };
     14 
---> 15 elx.align(**align_channels_parameter);

~/ClearMap2/ClearMap/Alignment/Elastix.py in align(fixed_image, moving_image, affine_parameter_file, bspline_parameter_file, result_directory, processes)
    550 
    551   if res != 0:
--> 552     raise RuntimeError('align: failed executing: ' + cmd);
    553 
    554   return result_directory

RuntimeError: align: failed executing: /home/yidan/elastix/bin/elastix -threads 1 -m /home/yidan/test/brain7test/resampled_autofluorescence.tif -f /home/yidan/test/brain7test/resampled.tif -p /home/yidan/ClearMap2/ClearMap/Resources/Alignment/align_affine.txt -out /home/yidan/test/brain7test/elastix_resampled_to_auto

**Comment by SaibotMagd** [comment]
Did you check if the raw/cfos file was stitched correctly? What dataset are you using? If you use slices you have to build a stitched stack before:
```
source = ws.source('raw');
  sink   = ws.filename('stitched')
  io.delete_file(sink)
  io.convert(source, sink, processes=None, verbose=True);
```
If it's in tiles you have to stitch it using the wobbly stitcher. Be aware of the missing autofluorescence files in the new 2020 Dataset for Cellmap, so this dataset can't work at all.

**Comment by umedtb** [comment]
Hi,

I have the same issue.  If I run `"result_directory" :  ws.filename('elastix_resampled_to_auto')`, I get 

> ValueError: Cannot find name for type 'elastix_resampled_to_auto'!

If I change to `"result_directory" :  ws.filename('resampled_to_auto')`, I get 

> RuntimeError: align: failed executing: /home/ClearMap/dataDisk/clearmap_git/ClearMap2/ClearMap/External/elastix/build/bin/elastix -threads 48 -m /home/ClearMap/scratchDisk/ImageSample/200929_Subject99_Saline _12-03-42/resampled_autofluorescence.tif -f /home/ClearMap/scratchDisk/ImageSample/200929_Subject99_Saline _12-03-42/resampled.tif -p /home/ClearMap/dataDisk/clearmap_git/ClearMap2/ClearMap/Resources/Alignment/align_affine.txt -out /home/ClearMap/scratchDisk/ImageSample/200929_Subject99_Saline _12-03-42/elastix_resampled_to_auto

In this case, an empty "elastix_resampled_to_auto" directory also appears in the image folder (along with other files).

Have you solved this issue? What does "-threads 48" in the error message could indicate to?

I have RTX 3090 which according to forums is not compatible with CUDA10 or older. Could this be an issue?

**Comment by umedtb** [comment]
I think I found the issue. elastix that comes in the external folder does not load properly. Here is the message: 

> error while loading shared libraries: libANNlib-4.9.so.1

Any ideas how to fix this?

**Comment by umedtb** [comment]
I have found the solution. The following lines must be added to .bashrc file (located in home folder):

export PATH=/home/.../ClearMap/External/elastix/build/bin:$PATH
export LD_LIBRARY_PATH=/home/.../ClearMap/External/elastix/build/bin:$LD_LIBRARY_PATH

From the web search it looks to be a recurring issue on CentOS.

**Comment by ChristophKirst** [comment]
This seems solved now that elastix is working. I close it.
We will try to include more documentation for this in the next updates of ClearMap.

**Comment by Hesham3esa** [comment]
can i please know how did you get over this problem?
RuntimeError: align: failed executing: /home/hesham/ClearMap2/ClearMap/External/elastix/build/bin/elastix -threads 16 -m /media/hesham/Extra/1.1 final/resampled_autofluorescence.tif -f /media/hesham/Extra/1.1 final/resampled.tif -p /home/hesham/ClearMap2/ClearMap/Resources/Alignment/align_affine.txt -out /media/hesham/Extra/1.1 final/elastix_resampled_to_auto

i tried the bashrc stuff and it didnt work
