### ISSUE TITLE
Comprehension issue: Why do we re-align the reference file? +Answer

### ISSUE THREAD

**Issue by SaibotMagd** [ClearAnatomics/ClearMap#25]
The pipeline use this code to "align the autofluorescence to the reference":
```
#%% Alignment - autoflourescence to reference
  
  # align autofluorescence to reference
  align_reference_parameter = {            
      #moving and reference images
      "moving_image" : reference_file,
      "fixed_image"  : ws.filename('resampled', postfix='autofluorescence'),
                                   
      
      #elastix parameter files for alignment
      "affine_parameter_file"  :  align_reference_affine_file,
      "bspline_parameter_file" :  align_reference_bspline_file,
      #directory of the alignment result
      "result_directory" :  ws.filename('auto_to_reference')
      };
  
  elx.align(**align_reference_parameter);
```
But the result isn't a re-aligned autofluorescence image, it is a re-aligned reference file. 

It seems unusual but I think I got the point: we're looking for 2 collections of transformation parameters:
1. 12 Affine Parameters for the transformation from cFos Image (the resampled Raw-File) to the resampled autofluorescence Image. Than use these Parameters to transform this autofluorescence image into a shape similar to the cFos Image to check the quality of this transformation and this lead to step 2.
2. Around 12.000 Bspline Parameters for the transformation from the transformed autofluorescence image (Step 1) to the Reference Atlas MR File. Than use these Parameters to transform the Reference File to check for the quality of these Parameters, but after this check we never use the transform Reference File anymore.

In the end we do a 3 step transformation for every coordinate the algorithm selected as a cell:
1. Resample the coordinate from high resolution to reference file resolution.
2. Use the Affine Parameters for a rough edge based alignment of the coordinates results from step 1.
3. Use the Bspline Parameters for a fine alignment of the coordinates from step 2.

So this is a one way track because there's an information-loss thanks to resample.

I hope I got it right and maybe this could be helpful for others. I close the issue after someone confirm my asumptions.

**Comment by nicolasrenier** [comment]
Hi, not sure if I can answer everything, but I will try!
- There is not much information loss during the resampling, as we use sub-pixel coordinates
- The reason the result of the alignment is the transformed reference file, is because of a peculiarity of Elastix: to perform a point transformation T, we need to perform the inverse image transformation T^(-1). So it looks backwards indeed when you check the results, but this is necessary to have the transformation matrix for the points going in the right direction.
I hope this answers your question?
