### ISSUE TITLE
Resampled Autofluorescence File is completely blank

### ISSUE THREAD

**Issue by SaibotMagd** [ClearAnatomics/ClearMap#26]
I started to work using our own dataset. I managed to create the resampled_autofluorescence.tif but it is completely black. I resliced the source images so there're all very similar and in great brightness. But still the result file is completely black in all pixes. 

Update: Quote from simpleITK Tutorial: "
A common issue with resampling resulting in an all black image is due to (a) incorrect specification of the desired output image's spatial domain (its meta-data); or (b) the use of the inverse of the transformation mapping from the output spatial domain to the resampled image."

What did I try:
- compare the cFos Images to the Autofluorescence because resample works for cFos; everything is now similar metadata, shape, brightness
- used inverse function, other interpolation methods and several other (wrong) orientations

**Comment by SaibotMagd** [comment]
I found the solution: "convert the tif-files to npy-files before resampling". Why? I don't know.

Quote from TubeMap Tutorial: "

```
Tile conversion

ClearMap makes use of accessing binary files in parallel. 
For optimal performance we recommend to convert the data to numpy files.
```

I think this is evidence that this isn't just "recommended". It actually changes the outcome.

**Comment by nicolasrenier** [comment]
I have to admit that certain tif formats can be a pain. We use ClearMap with the ome tiffs, but sometimes when we import tiff data coming from other sources it can be a problem. My recommendation is to convert the files to a less capricious format, such as the npy arrays, or I found nrrd works well for the most part. But depending on your sources, this might take a few tries to get the right format that can be opened with the tifffile library. ImageJ with BioFormat can really help in most cases to do these conversions.

**Comment by ZachPenn** [comment]
Thanks for posting your fix to this @SaibotMagd!  I ran into the same issue with .tif stack files, and really didn't want to continue dealing with folders of thousands of ome.tif files -- the conversion to npy worked great for me.
