### ISSUE TITLE
Cell Detection Parameter?

### ISSUE THREAD

**Issue by ywang219** [ClearAnatomics/ClearMap#28]
Hello, what are those serial numbers mean with the #, and how can we apply them?

processing_parameter = cells.default_cell_detection_processing_parameter.copy();
  processing_parameter.update(
      processes = None, # 'serial',
      size_max = 20, #100, #35,
      size_min = 11,# 30, #30,
      overlap  = 10, #32, #10,
      verbose = True
      )

**Comment by SaibotMagd** [comment]
I talked to Mr. Renier about this. He said all of these parameters are just for processing purposes, it don't change the outcome at all. You should use them to adjust the cell-detection to your hardware. I just adjust the number of processes till I nearly run out of working memory. On my Intel® Xeon CPU E5-1620 v4 @ 3.50GHz × 8 using 64GB RAM I can use 3-4 processes. 

PS: special hint this is the most cost intensive step in the cellmap pipeline. You will need about 4-times the storage space of your raw data file and about 50% of this have to be working memory (i.e. example Data 1267 cfos file is 17.1GB in total; the outcome file of this step is 68.5GB and you need at least 40GB of working memory). For the larger files I use a huge swap drive so the runtime is pretty long.

**Comment by ywang219** [comment]
> I talked to Mr. Renier about this. He said all of these parameters are just for processing purposes, it don't change the outcome at all. You should use them to adjust the cell-detection to your hardware. I just adjust the number of processes till I nearly run out of working memory. On my Intel® Xeon CPU E5-1620 v4 @ 3.50GHz × 8 using 64GB RAM I can use 3-4 processes.
> 
> PS: special hint this is the most cost intensive step in the cellmap pipeline. You will need about 4-times the storage space of your raw data file and about 50% of this have to be working memory (i.e. example Data 1267 cfos file is 17.1GB in total; the outcome file of this step is 68.5GB and you need at least 40GB of working memory). For the larger files I use a huge swap drive so the runtime is pretty long.

Thank you so much! Man yes the code can take such a long time. Would you say the default 20,11,10 take the least working memory?

**Comment by SaibotMagd** [comment]
> 
> Thank you so much! Man yes the code can take such a long time. Would you say the default 20,11,10 take the least working memory?

No I said I didn't really tested this. I just watched for the best CPU:Memory Ratio by adjusting the number of processes and let it run over night. We're planning to buy a pc upgrade after I did a successfull analysis on our own dataset, so I never really prioritize this.

**ups, I missed to answer the question:**
The "#" numbers are only suggestions you can try if you want to. In the end you should find a way to estimate good parameters for an optimal performance on your system.

**Comment by nicolasrenier** [comment]
Thanks a lot for the answers: indeed, the processing parameters have to be adjusted to your machine. To make sure the computation doesn't take forever, it is important to never run out of RAM, and try at all costs to avoid going in the swap. Using swap memory will dramatically slow down the processing. It is better to try using less processors or smaller chunks depending on your available RAM, but for super large datasets, of course the more RAM the better!

**Comment by ChristophKirst** [comment]
Just to answer the original question: 'serial' can be used to run the pipeline in serial with out parallelization.
This can be useful for testing purposes and better access to error messages.
