### ISSUE TITLE
Auto_to_resample file is zoomed in (affine alignment parameters miscalculated)

### ISSUE THREAD

**Issue by SaibotMagd** [ClearAnatomics/ClearMap#29]
I used our own dataset for the first time after running the Cellmap Pipeline using all Datasets you provided. Our Dataset is a little bit twisted (about -5 degree on the x-axis). The resample_to_auto file looks great like both resampled files. But the auto_to_resample file got a "zoomed in" look. 

Where could this problem come from? Could it have something to do with the twist? Shouldn't the affine alignment correct for something like that?

**Update: what did I try:**
- rotate the source pictures so the alignment becomes easier
- adjust the brightness of the autofluorescence picture so more structures inside the tissue are usable

I found out that the auto_to_resample file is nearly static not only zoomed in (i.e. every slice is very similar). The amount of transformation-parameters is poor (normally I got about 11340 here only 5300). 

The last 3 affine parameters are wrong calculated by elastix. In the first alignmentstep there're:
```
(TransformParameters 1.005806 -0.000168 0.007140 -0.000562 1.002287 -0.006515 0.000080 -0.000762 1.019741 
-0.058954 -0.004397 -0.143601)
```
in the Second:
```
(TransformParameters 1.018400 0.017734 -0.008881 0.001208 0.894661 -0.038549 0.003045 0.209495 -0.026565 
81.829106 48.647958 127.684375)
```
So it's obvious the last 3 parameters are way to large. Why? I don't know.

PS: yes I rotated the reference atlas file so it matches the orientation of my dataset

**Comment by SaibotMagd** [comment]
**Update:** it seems like the autofluorescence picture got a very bright border. Could this lead to the wrong calculation of translation parameters (last 3 parameters in the affine parameter array)? Probably, so how to solve it?
It seems like quality of the autofluorescence data just isn't good enough. I couldn't find out how to validate what "good" is. Hopefully the upcoming samples will clear this out.

**Comment by ywang219** [comment]
Hello, 
Thank you for sharing your troubleshooting steps here. Could you elaborate if you got a better alignment for the new samples? 

I have run into issues on alignment quality too, some brains have bright spots on the borders, and some have a little distorted brain regions. Do you think it could be how the brains were orientated in the light-sheet? We tried to have them run under the same conditions, same orientations...
