### ISSUE TITLE
aligned pics look distorted 

### ISSUE THREAD

**Issue by ywang219** [ClearAnatomics/ClearMap#30]
![image](https://user-images.githubusercontent.com/67708910/89339728-7f9f5700-d653-11ea-8ba6-1c5d7932b9e4.png)

Hello,

I am running around 50 brain slides, but the alignment looks distorted? Is this a problem when running a smaller sample instead of whole brain?

**Comment by SaibotMagd** [comment]
What dataset is this? On one hand, obviously the orientation of the atlas don't match the dataset (in result1 the cerebellum is on top in all other pictures on bottom left). On the other, you don't use the reference for the resample_to_auto (result1) picture.

**Comment by ywang219** [comment]
> What dataset is this? On one hand, obviously the orientation of the atlas don't match the dataset (in result1 the cerebellum is on top in all other pictures on bottom left). On the other, you don't use the reference for the resample_to_auto (result1) picture.

![image](https://user-images.githubusercontent.com/67708910/89455495-48927980-d717-11ea-8422-0a678b97a396.png)
I changed the parameters so the orientation looks ok. But the alignments are still funky. I used my own dataset, only part of the whole brain.

**Comment by ywang219** [comment]
> > What dataset is this? On one hand, obviously the orientation of the atlas don't match the dataset (in result1 the cerebellum is on top in all other pictures on bottom left). On the other, you don't use the reference for the resample_to_auto (result1) picture.
> 
> ![image](https://user-images.githubusercontent.com/67708910/89455495-48927980-d717-11ea-8422-0a678b97a396.png)
> I changed the parameters so the orientation looks ok. But the alignments are still funky. I used my own dataset, only part of the whole brain.

update: I aligned the whole brain using another dataset which looks a lot better. the only problem is with the auto-to-reference alignment which looks like a black shadow appearing somewhere in the center eating away the brain as I scroll to the right.  
![Screenshot from 2020-08-05 16-41-30](https://user-images.githubusercontent.com/67708910/89474804-7be6ff80-d73b-11ea-8ee3-7dc3b83dd054.png)
![Screenshot from 2020-08-05 16-42-31](https://user-images.githubusercontent.com/67708910/89474805-7db0c300-d73b-11ea-9ce4-33bd7685a26a.png)
![Screenshot from 2020-08-05 16-42-56](https://user-images.githubusercontent.com/67708910/89474809-80131d00-d73b-11ea-9099-bcc8a688caf6.png)

**Comment by SaibotMagd** [comment]
For me it really seems like the reference file isn't sliced and/or rotated correctly. Can you compare the "resample_autofluorescence.tif" to the "ABA_25um_reference__3_-2_1__slice_None_None...tif"-file (it's the version for my dataset I'm working on)?

**Comment by nicolasrenier** [comment]
It looks like to me that you are trying the align a half-brain dataset with a full brain reference? With the half brain dataset, you should crop the reference to match the anatomical coverage of the dataset you are trying to align. This can be done with a slice(1,246) in the z axis for instance for the dataset provided online.
