### ISSUE TITLE
gr[tp].sub_slice

### ISSUE THREAD

**Issue by saskra** [ClearAnatomics/ClearMap#31]
https://github.com/ChristophKirst/ClearMap2/blob/eca29347dbcb15e74c78f157ab0f4fb58cf0d4e7/ClearMap/Scripts/TubeMap.py#L742

Is that intentionally or accidentally a "gr", because in the other lines it says "grt"?

Where does this "grt" variable even come from?

**Comment by SaibotMagd** [comment]
Yes seems obvious it's a typo.

**Comment by saskra** [comment]
Thanks, then I will rename it.

**Comment by saskra** [comment]
Is it possible that it actually should be called **grp**?

https://github.com/ChristophKirst/ClearMap2/blob/bb6b4a8e3318bb5350758028f88ec562c24a69e1/ClearMap/Environment.py#L70

https://github.com/ChristophKirst/ClearMap2/blob/dc10aee0b2405eaa35bfb85095348f566330a59f/ClearMap/Analysis/Graphs/GraphGt.py#L1295

**Comment by ChristophKirst** [comment]
These are just examples to extract some regions with anatomical meaning, not really relevant to the script.

grt or gr should be graph.

Corrected in the new push and commented out to not cause more confusion.
