### ISSUE TITLE
no tmp/elastix_output/outputpoints.bin

### ISSUE THREAD

**Issue by ywang219** [ClearAnatomics/ClearMap#34]
Hi, when I do cell alignment the following error occurred. it seems that there the file could not be found. is it a naming error?

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-24-9949172052d1> in <module>
     24 coordinates = np.array([source[c] for c in 'xyz']).T;
     25 
---> 26 coordinates_transformed = transformation(coordinates);

<ipython-input-24-9949172052d1> in transformation(coordinates)
     12                   coordinates, sink=None,
     13                   transform_directory=ws.filename('resampled_to_auto'),
---> 14                   binary=True, indices=False);
     15 
     16   coordinates = elx.transform_points(

~/ClearMap2/ClearMap/Alignment/Elastix.py in transform_points(source, sink, transform_parameter_file, transform_directory, indices, result_directory, temp_file, binary)
    958   else:
    959     if binary:
--> 960       transpoints = read_points(os.path.join(outdirname, 'outputpoints.bin'), indices = indices, binary = True);
    961     else:
    962       transpoints = read_points(os.path.join(outdirname, 'outputpoints.txt'), indices = indices, binary = False);

~/ClearMap2/ClearMap/Alignment/Elastix.py in read_points(filename, indices, binary)
    811 
    812   if binary:
--> 813     with open(filename) as f:
    814       index = np.fromfile(f, dtype=np.int64, count = 1)[0];
    815       #print(index)

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/elastix_output/outputpoints.bin'

**Comment by SaibotMagd** [comment]
Did you check if all 3 alignment files are in their particular directories?

```
elastix_resampled_to_auto -> TransformParameters.0.txt (12 affine transformation parameters)
elastix_auto_to_reference -> TransformParameter.0.txt (12 affine transformation parameters)
elastix_auto_to_reference -> TransformParameter.1.txt (about 11340 Bspline transformation parameters)
```

Also check if he actually found coordinates to transform ("coordinates" not empty).

**Comment by ywang219** [comment]
> Did you check if all 3 alignment files are in their particular directories?
> 
> ```
> elastix_resampled_to_auto -> TransformParameters.0.txt (12 affine transformation parameters)
> elastix_auto_to_reference -> TransformParameter.0.txt (12 affine transformation parameters)
> elastix_auto_to_reference -> TransformParameter.1.txt (about 11340 Bspline transformation parameters)
> ```
> 
> Also check if he actually found coordinates to transform ("coordinates" not empty).

seems like all 3 alignment files are in the directories (transforparameters.1.txt has 34500 parameters)
I checked the coordinates: 
In [10]: coordinates                                                            
Out[10]: 
array([[   0,  355,    0],
       [   0,  359,    0],
       [   0,  583,    0],
       ...,
       [2006, 2008,   67],
       [2006, 2058,   66],
       [2006, 2159,   67]])

In [11]:

**Comment by ywang219** [comment]
> Did you check if all 3 alignment files are in their particular directories?
> 
> ```
> elastix_resampled_to_auto -> TransformParameters.0.txt (12 affine transformation parameters)
> elastix_auto_to_reference -> TransformParameter.0.txt (12 affine transformation parameters)
> elastix_auto_to_reference -> TransformParameter.1.txt (about 11340 Bspline transformation parameters)
> ```
> 
> Also check if he actually found coordinates to transform ("coordinates" not empty).

Seems like there are 2 files in the tmp/elastix_output directory: outputpoints.txt  transformix.log. There is no binary file for outputpoints?

**Comment by SaibotMagd** [comment]
> Seems like there are 2 files in the tmp/elastix_output directory: outputpoints.txt transformix.log. There is no binary file for outputpoints?

I think it is "cells.npy" created after running the transformation function in the pipeline. So it seems really temporarly, what function creates the bin?

I just traced the function call and got the outcome:"
transformix is started at Tue Aug 18 11:23:37 2020.

```
which transformix:   /home/user/anaconda3/clearmap/ClearMap2/ClearMap/External/elastix/build/bin/transformix
transformix runs at: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  Linux 4.18.0-193.6.3.el8_2.x86_64 (x64), #1 SMP Wed Jun 10 11:09:32 UTC 2020
  with 64077 MB memory, and 4 cores @ 3721 MHz.
Running transformix with parameter file "/home/user/anaconda3/clearmap/ClearMap2/ClearMap/Tests/Data/CNI_Data/elastix_auto_to_reference/TransformParameters.1.txt".

Reading the elastix parameters from file ...

Installing all components.
InstallingComponents was successful.

ELASTIX version: 4.900
Command line options from ElastixBase:
-in       unspecified, so no input image specified
-out      /tmp/elastix_output/
-threads  unspecified, so all available threads are used
-tp       /home/user/anaconda3/clearmap/ClearMap2/ClearMap/Tests/Data/CNI_Data/elastix_auto_to_reference/TransformParameters.1.txt
-def      /tmp/elastix_input.bin
-jac      unspecified, so no det(dT/dx) computed
-jacmat   unspecified, so no dT/dx computed
Calling all ReadFromFile()'s ...
Reading the elastix parameters from file ...

  Calling all ReadFromFile()'s took 0.002936 s
Transforming points ...
  The transform is evaluated on some points, specified in a binary input point file.
  Reading binary input point file: /tmp/elastix_input.bin
  Input points are specified in world coordinates.
  Number of specified input points: 3318740
  The input points are transformed.
  The transformed points are saved in: /tmp/elastix_output/outputpoints.bin
  Transforming points done, it took 6.28s
Compute determinant of spatial Jacobian ...
  The command-line option "-jac" is not used, so no det(dT/dx) computed.
  Computing determinant of spatial Jacobian done, it took 0.00s
Compute spatial Jacobian (full matrix) ...
  The command-line option "-jacmat" is not used, so no dT/dx computed.
  Computing spatial Jacobian done, it took 0.00s

transformix has finished at Tue Aug 18 11:23:43 2020.
Total time elapsed: 6.3s.

```
So he seems to create the binary file himself in the process.

**Comment by ywang219** [comment]
> > Seems like there are 2 files in the tmp/elastix_output directory: outputpoints.txt transformix.log. There is no binary file for outputpoints?
> 
> I think it is "cells.npy" created after running the transformation function in the pipeline. So it seems really temporarly, what function creates the bin?
> 
> I just traced the function call and got the outcome:"
> transformix is started at Tue Aug 18 11:23:37 2020.
> 
> ```
> which transformix:   /home/user/anaconda3/clearmap/ClearMap2/ClearMap/External/elastix/build/bin/transformix
> transformix runs at: xxxxxxxxxxxxxxxxxxxxxxxxxxx
>   Linux 4.18.0-193.6.3.el8_2.x86_64 (x64), #1 SMP Wed Jun 10 11:09:32 UTC 2020
>   with 64077 MB memory, and 4 cores @ 3721 MHz.
> Running transformix with parameter file "/home/user/anaconda3/clearmap/ClearMap2/ClearMap/Tests/Data/CNI_Data/elastix_auto_to_reference/TransformParameters.1.txt".
> 
> Reading the elastix parameters from file ...
> 
> Installing all components.
> InstallingComponents was successful.
> 
> ELASTIX version: 4.900
> Command line options from ElastixBase:
> -in       unspecified, so no input image specified
> -out      /tmp/elastix_output/
> -threads  unspecified, so all available threads are used
> -tp       /home/user/anaconda3/clearmap/ClearMap2/ClearMap/Tests/Data/CNI_Data/elastix_auto_to_reference/TransformParameters.1.txt
> -def      /tmp/elastix_input.bin
> -jac      unspecified, so no det(dT/dx) computed
> -jacmat   unspecified, so no dT/dx computed
> Calling all ReadFromFile()'s ...
> Reading the elastix parameters from file ...
> 
>   Calling all ReadFromFile()'s took 0.002936 s
> Transforming points ...
>   The transform is evaluated on some points, specified in a binary input point file.
>   Reading binary input point file: /tmp/elastix_input.bin
>   Input points are specified in world coordinates.
>   Number of specified input points: 3318740
>   The input points are transformed.
>   The transformed points are saved in: /tmp/elastix_output/outputpoints.bin
>   Transforming points done, it took 6.28s
> Compute determinant of spatial Jacobian ...
>   The command-line option "-jac" is not used, so no det(dT/dx) computed.
>   Computing determinant of spatial Jacobian done, it took 0.00s
> Compute spatial Jacobian (full matrix) ...
>   The command-line option "-jacmat" is not used, so no dT/dx computed.
>   Computing spatial Jacobian done, it took 0.00s
> 
> transformix has finished at Tue Aug 18 11:23:43 2020.
> Total time elapsed: 6.3s.
> ```
> 
> So he seems to create the binary file himself in the process.

Thank you! How did you do this "call" function? That's strange mine doesn't have the binary file. I am running CellMap, maybe theres something different with the code? 

Do you mean the transformation as in alignment to the atlas?

**Comment by SaibotMagd** [comment]
> Thank you! How did you do this "call" function? That's strange mine doesn't have the binary file. I am running CellMap, maybe theres something different with the code?
> 
> Do you mean the transformation as in alignment to the atlas?

Elastix creates the bin-file by itself. I'm running the transformation function and trace it like that:
```
  import sys
  import trace
  tracer = trace.Trace(
      ignoredirs=[sys.prefix, sys.exec_prefix],
      trace=1, count=1)
  
  
  #%% Cell alignment
  source = ws.source('cells', postfix='filtered')
  
  def transformation(coordinates):
    coordinates = res.resample_points(
                    coordinates, sink=None, orientation=None, 
                    source_shape=io.shape(ws.filename('stitched')), 
                    sink_shape=io.shape(ws.filename('resampled')));
    
    coordinates = elx.transform_points(
                    coordinates, sink=None, 
                    transform_directory=ws.filename('resampled_to_auto'), 
                    binary=True, indices=False);
    
    coordinates = elx.transform_points(
                    coordinates, sink=None, 
                    transform_directory=ws.filename('auto_to_reference'),
                    binary=True, indices=False);
      
    return coordinates;
    
  
  coordinates = np.array([source[c] for c in 'xyz']).T;
  
  coordinates_transformed = transformation(coordinates);
  tracer.run('transformation(coordinates)')
  tracer.results().write_results(show_missing=True, coverdir=".")
```

**Comment by ywang219** [comment]
> > Thank you! How did you do this "call" function? That's strange mine doesn't have the binary file. I am running CellMap, maybe theres something different with the code?
> > Do you mean the transformation as in alignment to the atlas?
> 
> Elastix creates the bin-file by itself. I'm running the transformation function and trace it like that:
> 
> ```
>   import sys
>   import trace
>   tracer = trace.Trace(
>       ignoredirs=[sys.prefix, sys.exec_prefix],
>       trace=1, count=1)
>   
>   
>   #%% Cell alignment
>   source = ws.source('cells', postfix='filtered')
>   
>   def transformation(coordinates):
>     coordinates = res.resample_points(
>                     coordinates, sink=None, orientation=None, 
>                     source_shape=io.shape(ws.filename('stitched')), 
>                     sink_shape=io.shape(ws.filename('resampled')));
>     
>     coordinates = elx.transform_points(
>                     coordinates, sink=None, 
>                     transform_directory=ws.filename('resampled_to_auto'), 
>                     binary=True, indices=False);
>     
>     coordinates = elx.transform_points(
>                     coordinates, sink=None, 
>                     transform_directory=ws.filename('auto_to_reference'),
>                     binary=True, indices=False);
>       
>     return coordinates;
>     
>   
>   coordinates = np.array([source[c] for c in 'xyz']).T;
>   
>   coordinates_transformed = transformation(coordinates);
>   tracer.run('transformation(coordinates)')
>   tracer.results().write_results(show_missing=True, coverdir=".")
> ```

It seems to have the same tracing results as yours. but the binary file is still not found ?

![image](https://user-images.githubusercontent.com/67708910/91100597-57839200-e61a-11ea-96fa-f8ebb7858335.png)

**Comment by ywang219** [comment]
The reason could be: "Number of specified input points:0 ". Has anyone come across with this issue?

**Comment by ywang219** [comment]
I set the binary = False to use the txt. file, which might be slower but works the same.
