### ISSUE TITLE
MemoryError: Unable to allocate XXX GiB for an array

### ISSUE THREAD

**Issue by saskra** [ClearAnatomics/ClearMap#36]
Since my computer can't calculate a whole brain, I wanted to use only a small part of the published data to test the TubeMap script. (In the end, I might use the pipeline for many medium-sized regions of interest.) I took the autofluorescence from the first brain 39L completely and from the raw data only four consecutive files from the middle (Y02, X05-06, Filter0000-0001).

```python
  #directories and files
  directory = '/home/saskra/PycharmProjects/ClearMap2/ClearMap/Tests/Data/TubeMap_Example'
  expression_raw      = 'Raw/14-16-41_tricocktail_UltraII[<Y,2> x <X,2>]_C00_UltraII Filter0001.ome.tif'
  expression_arteries = 'Raw/14-16-41_tricocktail_UltraII[<Y,2> x <X,2>]_C00_UltraII Filter0000.ome.tif'
  expression_auto     = 'Autofluorescence/14-02-13_auto_UltraII_C00_xyz-Table Z<Z,4>.ome.tif'
```
But I get this error message:

```shell
transformix has finished at Tue Aug 11 15:32:15 2020.
Total time elapsed: 12.1s.
/home/saskra/PycharmProjects/ClearMap2/ClearMap/Alignment/Annotation.py:459: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  label[valid] = atlas[indices];
Traceback (most recent call last):
  File "/home/saskra/anaconda3/envs/ClearMap/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-788a7e8ab86d>", line 1, in <module>
    runfile('/home/saskra/PycharmProjects/ClearMap2/ClearMap/Scripts/TubeMap.py', wdir='/home/saskra/PycharmProjects/ClearMap2/ClearMap/Scripts')
  File "/snap/pycharm-professional/211/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-professional/211/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Scripts/TubeMap.py", line 527, in <module>
    edge_geometry_properties = {'coordinates_atlas' : 'distance_to_surface'});
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Analysis/Graphs/GraphGt.py", line 1366, in transform_properties
    values = transformation(values);
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Scripts/TubeMap.py", line 522, in distance
    d = distance_atlas[x,y,z];
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/IO/TIF.py", line 109, in __getitem__
    return array[slicing_xy];
MemoryError: Unable to allocate 662. GiB for an array with shape (298039, 298039) and data type float64
```

It is true that I do not have that much memory available - but I think that I do not need it for this ROI. Does anyone have any advice for me on where to change the script to use only the actual size of my selected region?

**Comment by SaibotMagd** [comment]
I don't know anything about this issue but I've got 2 questions: Did you convert the files to npy? For me this makes a huge difference. Do you have any idea why he try to use float64? Because the source is only float16. I would check this.

**Comment by saskra** [comment]
Yes, the files were automatically converted to npy. And I will check, where the 16 bit become 64.

**Comment by saskra** [comment]
I checked that none of the files of the interim results contains float64 - so I do not know where it comes from and how to change it. But I also wonder how to change the shape to the much smaller one of my ROI (766 * 1306 * 3770).

**Comment by SaibotMagd** [comment]
> 
> 
> I checked that none of the files of the interim results contains float64 - so I do not know where it comes from and how to change it. But I also wonder how to change the shape to the much smaller one of my ROI (766 * 1306 * 3770).

I think you can use a debug-testset for this. (Tutorial part "create test data")

**Comment by saskra** [comment]
Thanks. That leads me to the next error message. I might open a new issue on that one in the next days. (Maybe simple renaming of directories will help again.)

```shell
Transforming vertex property: coordinates -> coordinates_atlas
Traceback (most recent call last):
  File "/snap/pycharm-professional/211/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/211/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Scripts/TubeMap.py", line 482, in <module>
    verbose=True);
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Analysis/Graphs/GraphGt.py", line 1366, in transform_properties
    values = transformation(values);
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Scripts/TubeMap.py", line 470, in transformation
    binary=True, indices=False);
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Alignment/Elastix.py", line 935, in transform_points
    transform_parameter_dir, transform_parameter_file = transform_directory_and_file(transform_parameter_file = transform_parameter_file, transform_directory = transform_directory);
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Alignment/Elastix.py", line 274, in transform_directory_and_file
    transform_parameter_file = transform_file(transform_parameter_dir);
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Alignment/Elastix.py", line 238, in transform_file
    files = os.listdir(result_directory);
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/saskra/PycharmProjects/ClearMap2/ClearMap/Tests/Data/TubeMap_Example/debug_elastix_resampled_to_auto'
python-BaseException
```

**Comment by SaibotMagd** [comment]
> 
> 
> Thanks. That leads me to the next error message. I might open a new issue on that one in the next days. (Maybe simple renaming of directories will help again.)

Yes you're right. This time, I actually had this error before.

**Comment by saskra** [comment]
Yes, renaming the two directories got me further - until the next error occurred, which is again an array too big and float64.

```shell
transformix has finished at Wed Aug 12 17:20:13 2020.
Total time elapsed: 0.8s.
/home/saskra/PycharmProjects/ClearMap2/ClearMap/Alignment/Annotation.py:459: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  label[valid] = atlas[indices];
Traceback (most recent call last):
  File "/snap/pycharm-professional/211/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/211/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Scripts/TubeMap.py", line 527, in <module>
    edge_geometry_properties = {'coordinates_atlas' : 'distance_to_surface'});
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Analysis/Graphs/GraphGt.py", line 1386, in transform_properties
    values = transformation(values);
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/Scripts/TubeMap.py", line 522, in distance
    d = distance_atlas[x,y,z];
  File "/home/saskra/PycharmProjects/ClearMap2/ClearMap/IO/TIF.py", line 103, in __getitem__
    array = self._tif.asarray(key = slicing_z, maxworkers=processes);
  File "/home/saskra/anaconda3/envs/ClearMap/lib/python3.7/site-packages/tifffile/tifffile.py", line 2366, in asarray
    result = stack_pages(pages, out=out, maxworkers=maxworkers)
  File "/home/saskra/anaconda3/envs/ClearMap/lib/python3.7/site-packages/tifffile/tifffile.py", line 11219, in stack_pages
    out = create_output(out, shape, dtype)
  File "/home/saskra/anaconda3/envs/ClearMap/lib/python3.7/site-packages/tifffile/tifffile.py", line 11300, in create_output
    return numpy.zeros(shape, dtype)
MemoryError: Unable to allocate 426. GiB for an array with shape (338652, 528, 320) and data type float64
python-BaseException
```

**Comment by SaibotMagd** [comment]
What command are you running? What is the size of your Ram/Swap right now (is it enough for this array)?

**Comment by saskra** [comment]
It is still the TubeMap main script I am trying to run: ClearMap/Scripts/TubeMap.py

I have 384GB RAM, so the error message is not wrong about that. I just doubt that it need this size for my small example.

**Comment by SaibotMagd** [comment]
> 
> 
> It is still the TubeMap main script I am trying to run: ClearMap/Scripts/TubeMap.py
> 
> I have 384GB RAM, so the error message is not wrong about that. I just doubt that it need this size for my small example.

I just think aloud. I'm still stucked in the cellmap pipeline because we need this one running, never really worked with tubemap. I could just go through the source code and look for irregularities, but don't have time for that. 

When I were you I would reduce the debug_dataset as much as possible so the pipeline will probably run (1x1x1 if neccessary) and trace the process.

**Comment by saskra** [comment]
Maybe I'm waiting for at least the problem with the file and directory names to be officially fixed.

In the meantime, I'm trying to extract from the big pipeline the functions that are especially interesting for me, such as skeletonization. But removing something supposedly unnecessary here doesn't seem to be easy either.

**Comment by ChristophKirst** [comment]
It seems that the detection of the shape of your file is no working (e.g (338652, 528, 320) looks wrong).
Thus, please try to locate which file triggers this error, what the actual shape of that file is so there is a way to fix this.

Try to not run the entire pipeline at once, but go through it step by step.

From other issues raised on here, I think some of the issues arise because the the pipelines in ClearMap might be viewed as scripts than can be run through at once. It is important to note that the pipelines are not scripts you can simply run through
without adapting the steps to your hardware and data. I recommend to go through each cell of that pipeline step by step until it works using the debug mode. If you stumble upon an error it will then be also easier to identify and fix what is going wrong (also for us). Once the pipeline works this way you can run it all at once and apply it to similar data sets by adapting the file names only.

Hope this helps.

**Comment by saskra** [comment]
> It is important to note that the pipelines are not scripts you can simply run through without adapting the steps to your hardware and data.

Thank you very much for the answer! I have now also come to the conclusion that I have to adapt much more than I had initially expected. For some steps like segmentation, it might even be easier if I just rewrote them for my data. But maybe I can at least learn from the speed-optimised stitching and skeletonisation steps.
