### ISSUE TITLE
Cellmaps Transform Coordinates Function leads to Coordinates outside the tissue

### ISSUE THREAD

**Issue by SaibotMagd** [ClearAnatomics/ClearMap#39]
I used the 2020er Example Dataset and every alignment step works pretty fine. I also did the cell detection step 2 times using 2 different thresholds 1800 and 2000. When I plot the coordinates of the cfos cells it seems pretty good:
![image](https://user-images.githubusercontent.com/67700096/91415450-59ce3200-e84e-11ea-928e-48ef5eb7d603.png)
(my own point plotter, not part of cellmap).
Also the coordinates seems good. But when I check for the transformed to reference coordinates they end up outside the tissue (some clusters are in slices larger than the largest slice in the reference file max(z) = 246):
![image](https://user-images.githubusercontent.com/67700096/91415731-c2b5aa00-e84e-11ea-92b9-98b18cb6a8c3.png)
... I don't know what's happen here. Something is wrong with the alignment but I don't know what it is.

I also checked the cells.csv directly:

```
print("Issue Size: ", ogSize)
print("max(x):", max(df['x']), " max(y):", max(df['y']), "max(z):", max(df['z']))
print("Reference Size", refSize)
print("max(xt):", max(df['xt']), " max(yt):", max(df['yt']), "max(zt):", max(df['zt']))
Issue Size:  [4555, 7218, 1030]
max(x): 4553.0  max(y): 7130.0 max(z): 1029.0
Reference Size [320, 528, 246]
max(xt): 300.9986608482074  max(yt): 526.9999750841395 max(zt): 282.5654691645599
```
PS: I cutted the "universe" area.

**Comment by ChristophKirst** [comment]
Hi, i am not 100% sure what exactly the problem is. 

The alignment routine is nonlinear and deforms the data to best match the atlas data. This can lead to regions that are deformed outside of the atlas if the alignment is not good. Also if you cut your reference file to be smaller than the actual data  you may get this effect.

Hope this helps ?

**Comment by SaibotMagd** [comment]
> Hi, i am not 100% sure what exactly the problem is.
> 
> The alignment routine is nonlinear and deforms the data to best match the atlas data. This can lead to regions that are deformed outside of the atlas if the alignment is not good. Also if you cut your reference file to be smaller than the actual data you may get this effect.
> 
> Hope this helps ?

Well I don't know right now, have to do a better validation. But it is the same answer Mr. Renier gave me before. We're preparing some new samples especially for the pipeline at the moment to do a proper validation soon.

**Comment by freblisna** [comment]
@SaibotMagd did you ever figure this out? I can't find problems with my alignment (merged stacks in fiji and red/green overlay looks precise) but the transformed coordinates look imprecise. The transformed coordinates broadly resemble the tissue but parts are clearly outside the tissue, whereas in the alignment those same regions look correctly registered (alignment looks good for both sample-to-auto and auto-to-ref )

**Comment by freblisna** [comment]
nevermind, figured out my issue... was created by downsampling/upsampling coordinates.
