### ISSUE TITLE
torch package not found

### ISSUE THREAD

**Issue by saskra** [ClearAnatomics/ClearMap#4]
https://github.com/ChristophKirst/ClearMap2/blob/d2ecc5cf3d5efe21b25687dae1294085863d5626/ClearMap.yml#L32

```bash
conda env create -f ClearMap.yml
Collecting package metadata (repodata.json): done
Solving environment: failed
ResolvePackageNotFound: 
  - torch
```

**Comment by ChristophKirst** [comment]
Only pytorch is needed, the yml file is updated in the new version
