### ISSUE TITLE
Confusing imports

### ISSUE THREAD

**Issue by saskra** [ClearAnatomics/ClearMap#40]
https://github.com/ChristophKirst/ClearMap2/blob/eca29347dbcb15e74c78f157ab0f4fb58cf0d4e7/ClearMap/Scripts/TubeMap.py#L34

https://github.com/ChristophKirst/ClearMap2/blob/eca29347dbcb15e74c78f157ab0f4fb58cf0d4e7/ClearMap/Scripts/TubeMap.py#L86

Just a comment and only one example, I already figured it out myself. I think this can be highly confusing, when you consider these search results (some of them even from the same file):

```python
import ClearMap.Alignment.Stitching.StitchingRigid as st
import ClearMap.Alignment.Stitching as st
import ClearMap.Analysis.Statistics.StatisticalTests as st
import ClearMap.Analysis.Statistics.GroupStatistics as st
import scipy.stats as st
```

**Comment by ChristophKirst** [comment]
To get the abbreviated names used in the ClearMap environment you are importing from

https://github.com/ChristophKirst/ClearMap2/blob/eca29347dbcb15e74c78f157ab0f4fb58cf0d4e7/ClearMap/Scripts/TubeMap.py#L34

check the [Environment.py](https://github.com/ChristophKirst/ClearMap2/blob/master/ClearMap/Environment.py) module you are importing the names from. 

There:

https://github.com/ChristophKirst/ClearMap2/blob/e09f44943064f4b10f55510f8c7b385c26b84566/ClearMap/Environment.py#L57

The other imports you are listing are all local to their modules and not related.
