### ISSUE TITLE
Problems recognizing images when running rigid z alignment

### ISSUE THREAD

**Issue by mkern16** [ClearAnatomics/ClearMap#50]
Hello all,

I've been trying to run cellmap now but keep running into problems at the rigid z alignment step. 

`layout = stw.WobblyLayout(expression=ws.filename('raw'), tile_axes=['X','Y'], overlaps=(400, 400));

st.align_layout_rigid_mip(layout, depth=[400, 400, None], max_shifts=[(-50,50),(-50,50),(-30,30)],
                          ranges = [None,None,None], background=(400, 100), clip=25000,
                           processes=None, verbose=True)

st.place_layout(layout, method='optimization', min_quality=-np.inf, lower_to_origin=True, verbose=True)

st.save_layout(ws.filename('layout', postfix='aligned_axis'), layout)
Traceback (most recent call last):

  File "<ipython-input-10-faec2d6b6a2c>", line 1, in <module>
    layout = stw.WobblyLayout(expression=ws.filename('raw'), tile_axes=['X','Y'], overlaps=(400, 400));

  File "G:\user\ClearMap2-master\ClearMap2-master\ClearMap\Alignment\Stitching\StitchingWobbly.py", line 721, in __init__
    strg.TiledLayout.__init__(self, sources = sources, expression = expression, tile_axes = tile_axes, tile_shape = tile_shape, tile_positions = tile_positions, positions = positions, overlaps = overlaps, alignments = alignments, position = position, shape = shape, dtype = dtype, order = order);

  File "G:\user\ClearMap2-master\ClearMap2-master\ClearMap\Alignment\Stitching\StitchingRigid.py", line 1906, in __init__
    sources, alignments, tile_positions = _initialize_tiles_from_expression(expression, tile_axes=tile_axes, tile_shape=tile_shape, tile_positions=tile_positions, overlaps=overlaps, positions=positions, alignments=alignments);

  File "G:\user\ClearMap2-master\ClearMap2-master\ClearMap\Alignment\Stitching\StitchingRigid.py", line 2243, in _initialize_tiles_from_expression
    raise ValueError('The expression does not have the named pattern %s' % n);

ValueError: The expression does not have the named pattern X`

I feel like this may be some issue with how the data is structured, in a way that clearmap can't recognize the x and y axes of the images. I acquired my original lightsheet images with the Zeiss Z1, and later converted the czi to a single tif for use in clearmap. From the clearmap documentation, I know this was first designed around a different microscope, though I don't know if the different systems actually format the images differently enough to cause an issue. Any help or insight in fixing this issue would be greatly appreciated.

**Comment by DCoss1995** [comment]
Hi! I have the same problem. Have you fixed it?
