### ISSUE TITLE
Can ClearMap2 be installed in windows

### ISSUE THREAD

**Issue by ZhenhongDu** [ClearAnatomics/ClearMap#52]
Hello！Sorry to bother you.
Can ClearMap2 be installed in windows?The graph-tool library seems cannot be installed on windows.Can I continue to use ClearMap2?

**Comment by ZhenhongDu** [comment]
The main function module I want to use is WobblyStitcher. StitchingWobbly.py file imports functions from the graph tool library.Can I only run it by installing a linux system

**Comment by ywang219** [comment]
Hi,
It would save you a lot of troubleshoot steps if you run on a linux system. I first tried on mac but switched to ubuntu virtual box due to the extra time spent. There are a lot of tutorials online using virtualbox. Good luck!

**Comment by ZhenhongDu** [comment]
@ywang219  Thanks a lot!
