### ISSUE TITLE
Speed up WobblyStitcher?

### ISSUE THREAD

**Issue by saskra** [ClearAnatomics/ClearMap#53]
Is there any advice on how to speed up the "wobbly alignment" step? I've been running it for a week now with 40 CPUs with no end in sight. I have 4 x 4 images (in three channels, but I'm currently using only one of them) of the size 2048 x 2048 x 132 (4.4 GB).

```python
stw.align_layout(layout,
				 axis_range=(None, None, 3),
				 max_shifts=[(-205, 205), (-205, 205), (-13, 13)],
				 axis_mip=None,
				 validate=dict(method='foreground', valid_range=(200, None), size=None),
				 prepare=dict(method='normalization', clip=None, normalize=True),
				 validate_slice=dict(method='foreground', valid_range=(200, 20000), size=1500),
				 prepare_slice=None,
				 find_shifts=dict(method='tracing', cutoff=3 * np.sqrt(2)),
				 processes=n_processes_stitch,
				 verbose=verbosity)
```

Edit: It gets stuck here every time:
```shell
Alignment: Wobbly slice alignment (1, 0)->(1, 1) along axis 2 done: elapsed time: 0:01:10.870
Alignment: Wobbly alignment (1, 0)->(2, 0) along axis 2 done: elapsed time: 0:07:02.808
Alignment: Wobbly alignment (1, 0)->(1, 1) along axis 2 done: elapsed time: 0:34:10.453
```

**Comment by ChristophKirst** [comment]
I don't think its the speed, We stitch much bigger data sets with half the CPUs in 45 min.

Do you walk through all the required previous alignment steps?

Also the max shifts are quite big in your case: We typically use -30,30. 

To tell you more about the problem, can you run it until it gets stuck, press Ctrl + C to interrupt the process and see where it stopped (or paste the output here)

**Comment by freblisna** [comment]
are you using the ome tif files? I fiind it runs orders of magnitude more quickly with the npy files than compared to the ome.tif's
