### ISSUE TITLE
Visualization show a window, but no image shown and became frozen

### ISSUE THREAD

**Issue by Shigeaki-Kanatani** [ClearAnatomics/ClearMap#56]
I am following tutorial of TubeMap on Linux. It works perfetly until visualization of the following codes.

filename = ws.file_list('raw')[0]
p3d.plot(filename)

The output looks fine (below), but it just showed a black window and became frozen.
Out[9]: [<ClearMap.Visualization.Qt.DataViewer.DataViewer at 0x7f281149fc30>]

Does anybody has an idea what is happening and how to fix this issue?

If I skipped the visualization step, the WobblyStitcher worked.

Best,

Shigeaki

**Comment by EdwinHernandezG** [comment]
If you are using spyder you can use @ChristophKirst  solution:

https://github.com/ChristophKirst/ClearMap2/issues/17#issuecomment-694561938

If you are using the Jupyter notebook you can use the magic code

`%gui qt`

**Comment by Shigeaki-Kanatani** [comment]
Dear Edwin,

Thank you for your help. I am using spyder and the solution you suggested worked.

Best,

Shigeaki
