### ISSUE TITLE
ClearMap/Tests/Data/Vasculature/vasculature_pre.npy is missing

### ISSUE THREAD

**Issue by slitvinov** [ClearAnatomics/ClearMap#6]
Many files which are used in tests are missing. For example,
`ClearMap/Tests/Data/Vasculature/vasculature_pre.npy`

**Comment by ChristophKirst** [comment]
Yes, the test data is huge so we did not include it in the repository for now.
If time permits, we might include smaller data sets at some point in the future.
Our priority is on releasing the software and documentation at this point.

**Comment by ChristophKirst** [comment]
You can download some raw data here:

https://osf.io/sa3x8/
