### ISSUE TITLE
Alignment of autofluorescence_to_reference looks bad

### ISSUE THREAD

**Issue by bhnrus** [ClearAnatomics/ClearMap#63]
Hi, 
When opening the result.1.mhd file with imageJ I get this blurry shady hemisphere that doesn't have the details of the resampled image or the reference atlas. The first alignment of resmpled_to_autofluorescence went well, when checking the result.0.mhd file on imageJ. Does anyone have any idea what happened? maybe it is my bspline.txt file?
Thanks!

![Screenshot of bad alignment auto_to_reference](https://user-images.githubusercontent.com/69247099/108703001-af8c4a00-7512-11eb-95b0-6bb1d488a4db.jpg)

**Comment by freblisna** [comment]
@bhnrus did you ever solve this? I'm wondering what you did if so.
