### ISSUE TITLE
Installing clearmap2 on windows

### ISSUE THREAD

**Issue by notevenclosee** [ClearAnatomics/ClearMap#65]
Hello,
I was trying to install clearmap2 on window with anaconda.
I cloned the repository with 
git clone https://github.com/ChristophKirst/ClearMap2.git
cd clearmap2
C:\Users\Analysis\ClearMap2> conda env create -f ClearMap.yml

Received the error message 
ResolvePackageNotFound:
-graph-tool
I tried "conda install graph-tool" and received "PackagesNotFoundError: The following packages are not available from current channels: - graph tool"

I searched on the anaconda website for the package and the most similar one is conda-forge / graph-tool 2.37. but it is only for linux64 and osx 64.
That's where I am stuck... Could you please provide some guidance on how to install it on windows?
Thank you
Sincerely
Anthea

**Comment by EdwinHernandezG** [comment]
Currently, there is no easy way to compile ClearMap on windows.
You can try WSL, but you will not be able to use the viewer and have to run ClearMap from the python console.

**Comment by JacobBumgarner** [comment]
Sorry that this isn't a great answer, but maybe this link can help you.
https://git.skewed.de/count0/graph-tool/-/wikis/installation-instructions#windows

**Comment by SaibotMagd** [comment]
Even if you could manage to solve this problem, you will run in even more troubles afterwards. I would'n recommend to waste your time in doing so. Try to use a VM insteed. I could manage to do nearly everything on a VM.

**Comment by ChristophKirst** [comment]
We currently do not support running ClearMap on Windows. While its probably possible to set things up to work it will take some time to solve. If you only want to try ClearMap a Linux Virtual Machine will be the easiest solution.
If you need to do high performance computing a dual boot machine Windows/Linux using Linux for ClearMap might be another solution.
