### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by JacobBumgarner** [ClearAnatomics/ClearMap#66]
Hello,
I'm attempting to use the skeletonization algorithms implemented into ClearMap. However, when I try to import the ClearMap.ImageProcessing.Skeletonization.Skeletonization file into my program, I'm returned with this error:

**clang: error: unsupported option '-fopenmp'
...
  File "/Users/deleted/opt/anaconda3/envs/myenv/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))

DistutilsExecError: command 'gcc' failed with exit status 1**

I've tried googling around but can't seem to find the solution to this problem. Any suggestions or help would be much appreciated. 

Thanks

**Comment by SaibotMagd** [comment]
I had this issue before but I can barely remember what I did to solve this. I think I just updated my gcc version.

**Comment by ChristophKirst** [comment]
This indicates you need to activate/install OpenMP in your gcc environment. 
 
See this issue:

https://github.com/ChristophKirst/ClearMap2/issues/15
