### ISSUE TITLE
Problem installing ClearMap2 on Linux

### ISSUE THREAD

**Issue by DCoss1995** [ClearAnatomics/ClearMap#70]
Hi! I am trying to install ClearMap2 on Linux, but I'm stuck with graph-tool module. Using conda, it isn't able to install the graph-tool module, and in particular the installation process is stuck on solving environment. Anyone had the same problem or knows how to solve it?

Thank you!

**Comment by Wifredoo** [comment]
Hi, I am able to run the code in python console with the ClearMap environment activated. 
<<< from ClearMap.Environment import * 
However, I also have the same error showing "no graph-tool" when I try to run it in the CellMap ipython file.

**Comment by freblisna** [comment]
Are you using "conda env create" or "conda install"? I'm using linux (CentOS v7.7.1908) , the installation didn't require manual "conda install" commands. Once the scripts are cloned from github, you only need to use "conda env create -f ClearMap.yml" from the ClearMap2 folder. Took 10ish minutes for this command to run. Afterward, imports and initializing should run smoothly.

**Comment by DCoss1995** [comment]
> 
> 
> Are you using "conda env create" or "conda install"? I'm using linux (CentOS v7.7.1908) , the installation didn't require manual "conda install" commands. Once the scripts are cloned from github, you only need to use "conda env create -f ClearMap.yml" from the ClearMap2 folder. Took 10ish minutes for this command to run. Afterward, imports and initializing should run smoothly.

**Comment by DCoss1995** [comment]
I will try as soon as possible and let ypu know. Thank you so much.

**Comment by austinhoag** [comment]
I had this same issue. Just spinning forever. I solved it by upgrading conda. I was (and still am) running the `conda env create -f ClearMap.yml` command to create the environment. It still did take ~5-10 minutes.
