### ISSUE TITLE
Wobblystitcher "!serial"

### ISSUE THREAD

**Issue by PTRRupprecht** [ClearAnatomics/ClearMap#79]
A very simple question. For the wobblystitcher, the argument "processes" is set to "serial".

stw.stitch_layout(layout, sink = ws.filename('stitched'), method = 'interpolation', processes='!serial', verbose=True)

Is this the same as setting the variable to "1"?

stw.stitch_layout(layout, sink = ws.filename('stitched'), method = 'interpolation', processes=1, verbose=True)

And if not, what is the difference?

Best wishes,
Peter

**Comment by stegiopast** [comment]
Good evening,

I'm currently using the CellMap Tool, but if the variable follows a similar logic in your case, the processes variable describes the number of processes you can run at the same time. I was able to exchange the string with an integer and define the number of parallel processes. Maybe it's worth a try.

Best wishes,
Stefan

**Comment by PTRRupprecht** [comment]
Dear Stefan,

Thank you very much for taking the time to reply. Yes, I know that the number of CPU processes can be set with this variable. However, I was wondering whether things were special about this specific function, and in particular I was wondering what the "!serial" option does. This process (stitching) can probably not be parallelized, and setting an arbitrary integer might simply crash the function. I would assume that the "!serial" option it's equivalent to processes=1, but maybe it's a bit more complicated.

Best wishes,
Peter

**Comment by PTRRupprecht** [comment]
To add to this discussion, I realized there is a difference between using the "!serial" and the "serial" option. In the example Tubemap code provided, one channel uses "!serial", the other "serial" (https://github.com/ChristophKirst/ClearMap2/blob/master/ClearMap/Scripts/TubeMap.py). Maybe this could be corrected or explained.

Independent of that, I noticed that stitching stops prematurely when I'm using the "!serial" option while stitching on a NAS server, not on a local disk. I get the following error:

<pre><code>Exception in thread Thread-20:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/ClearMap/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/envs/ClearMap/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anaconda3/envs/ClearMap/lib/python3.6/concurrent/futures/process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "/home/user/anaconda3/envs/ClearMap/lib/python3.6/concurrent/futures/process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "/home/user/anaconda3/envs/ClearMap/lib/python3.6/multiprocessing/queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "/home/user/anaconda3/envs/ClearMap/lib/python3.6/multiprocessing/queues.py", line 83, in put
    raise Full
queue.Full</pre></code>

Maybe somebody knows how to solve this problem by any chance?

**Comment by nicolasrenier** [comment]
I everyone, sorry for the late reply, this was brought to my attention by Charly Rousseau: the "!serial" option is just a quick way to say that the processing is parallel (anything you write in this argument that is not "serial" will be understood as "parallel"). Then, if the processing is parallel, then you can select a number of processors in "processes".

I hope this clarifies it.

If the parallel processing crashes, you can also try to change the as_memory parameter as "False".

**Comment by PTRRupprecht** [comment]
Thank you, this clear now.
