### ISSUE TITLE
Cannot find name for type 'elastix resampled to auto'!

### ISSUE THREAD

**Issue by bwtan** [ClearAnatomics/ClearMap#8]
Hi Christoph,

I met an issue when running CellMap, in this section:

`#%% Aignment - resampled to autofluorescence
  
  # align the two channels
  align_channels_parameter = {            
      #moving and reference images
      "moving_image" : ws.filename('resampled', postfix='autofluorescence'),
      "fixed_image"  : ws.filename('resampled'),
      
      #elastix parameter files for alignment
      "affine_parameter_file"  : align_channels_affine_file,
      "bspline_parameter_file" : None,
      
      #directory of the alig'/home/nicolas.renier/Documents/ClearMap_Ressources/Par0000affine.txt',nment result
      "result_directory" :  ws.filename('**elastix_resampled_to_auto**')
      }; `

The error message is when accessing Workspace.py:
cannot find name for type 'elastix_resampled_to_auto'!

Do you have any idea why this may happen?

**Comment by alexcwsmith** [comment]
For me, removing "elastix" from the filename and instead just using 

`"result_directory" :  ws.filename('resampled_to_auto')`

is working fine, as this is the specified name in the Workspace.py script. You will likely need to do the same for the auto_to_reference parameter. Maybe Christoph can weigh in if this is accurate, but it seemed to be fine for me.

**Comment by ChristophKirst** [comment]
This should work.  

You can always check the possible workspace names via

> ws.file_type_to_name

Or define your own file types via the update routine.
